
//generated by flower.py
/**
 * 花卉杂交
 */
export const flowers = {
    "rose": [
        {
            "parents": [
                {
                    "color": "red",
                    "gene": "RRyyWWSs",
                    "desc": "种子"
                },
                {
                    "color": "yellow",
                    "gene": "rrYYWWss",
                    "desc": "种子"
                }
            ],
            "children": [
                {
                    "color": "orange",
                    "gene": "RrYyWWss",
                    "desc": "50%"
                },
                {
                    "color": "yellow",
                    "gene": "RrYyWWSs",
                    "desc": "50%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "white",
                    "gene": "rryyWwss",
                    "desc": "种子"
                },
                {
                    "color": "white",
                    "gene": "rryyWwss",
                    "desc": "种子"
                }
            ],
            "children": [
                {
                    "color": "purple",
                    "gene": "rryywwss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rryyWWss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rryyWw",
                    "desc": "50%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "purple",
                    "gene": "rryywwss",
                    "desc": "一号紫"
                },
                {
                    "color": "yellow",
                    "gene": "rrYYWWss",
                    "desc": "种子"
                }
            ],
            "children": [
                {
                    "color": "white",
                    "gene": "rrYyWwss",
                    "desc": "100%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "white",
                    "gene": "rrYyWwss",
                    "desc": "一号白"
                },
                {
                    "color": "purple",
                    "gene": "rryywwss",
                    "desc": "一号紫"
                }
            ],
            "children": [
                {
                    "color": "purple",
                    "gene": "rrYywwss",
                    "desc": "25%"
                },
                {
                    "color": "purple",
                    "gene": "rryywwss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rryyWwss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rrYyWwss",
                    "desc": "25%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "purple",
                    "gene": "rrYywwss",
                    "desc": "二号紫"
                },
                {
                    "color": "purple",
                    "gene": "rrYywwss",
                    "desc": "二号紫"
                }
            ],
            "children": [
                {
                    "color": "white",
                    "gene": "rrYYwwss",
                    "desc": "25%"
                },
                {
                    "color": "purple",
                    "gene": "rrYywwss",
                    "desc": "25%"
                },
                {
                    "color": "purple",
                    "gene": "rryywwss",
                    "desc": "50%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "orange",
                    "gene": "RrYyWWss",
                    "desc": "一号橙"
                },
                {
                    "color": "white",
                    "gene": "rrYYwwss",
                    "desc": "二号白"
                }
            ],
            "children": [
                {
                    "color": "orange",
                    "gene": "RrYYWwss",
                    "desc": "25%"
                },
                {
                    "color": "red",
                    "gene": "RrYyWwss",
                    "desc": "25%"
                },
                {
                    "color": "yellow",
                    "gene": "rrYYWwss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rrYyWwss",
                    "desc": "25%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "orange",
                    "gene": "RrYYWwss",
                    "desc": "二号橙"
                },
                {
                    "color": "white",
                    "gene": "rrYYwwss",
                    "desc": "二号白"
                }
            ],
            "children": [
                {
                    "color": "red",
                    "gene": "RrYYwwss",
                    "desc": "25%"
                },
                {
                    "color": "orange",
                    "gene": "RrYYWwss",
                    "desc": "25%"
                },
                {
                    "color": "yellow",
                    "gene": "rrYYWwss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rrYYwwss",
                    "desc": "25%"
                }
            ]
        },
        {
            "parents": [
                {
                    "color": "red",
                    "gene": "RrYYwwss",
                    "desc": "一号红"
                },
                {
                    "color": "red",
                    "gene": "RrYYwwss",
                    "desc": "一号红"
                }
            ],
            "children": [
                {
                    "color": "blue",
                    "gene": "RRYYwwss",
                    "desc": "25%"
                },
                {
                    "color": "red",
                    "gene": "RrYYwwss",
                    "desc": "25%"
                },
                {
                    "color": "white",
                    "gene": "rryyWwss",
                    "desc": "25%"
                }
            ]
        }
    ],
    "null": [
        {}
    ]
};
