# coding=utf-8
import openpyxl
import json

tpl = '''
//generated by flower.py
/**
 * 花卉杂交
 */
export const flowers = {
%s
};
'''

fileName = 'flower'

propertyKeys = ['color', 'gene', 'desc']

data = {}

def main():
	readConfig()
	writeConfig()

def readConfig():
	print('开始读取配置...', end='\n')
	
	filePath = '.\\' + fileName + '.xlsx'
	workbook = openpyxl.load_workbook(filePath)
	worksheet = workbook.active
	
	print('配置文件路径：', filePath ,end='\n')
	
	dicts = {}
	for cell_col in list(worksheet.columns)[0][1:]:
		if cell_col.value not in dicts:
			dicts[cell_col.value] = []

	for row_index, row_item in enumerate(worksheet.rows):
		propertys = {}
		for col_index, cell in enumerate(list(row_item)):
			if row_index == 0 or col_index == 0 or cell.value == None:
				continue 

			propertyKey = worksheet[1][col_index].value
			if propertyKey not in propertys:
				propertys[propertyKey] = []

			values = cell.value.split(",")
			item = {}
			for index, value in enumerate(values):
				item[propertyKeys[index]] = value

			propertys[propertyKey].append(item)
		if row_index == 0:
			continue
		dicts[worksheet[row_index+1][0].value].append(propertys)
	global data
	data = dicts
	print('读取配置成功...', end='\n')
	# print(dicts, end="\n")

def writeConfig():
	print('开始导出配置...', end='\n')
	
	filePath = '.\\' + fileName + '.js'
	with open(filePath, 'w', encoding='UTF-8') as f:
		print('格式化输出格式...', end='\n')
		json_dicts=json.dumps(data,indent=4,ensure_ascii=False)
		json_dicts = json_dicts.lstrip('{\n').rstrip('}\n')
		f.write(tpl % json_dicts)
		
	print('导出路径：', filePath ,end='\n')
if __name__ == "__main__":
	main()
	
input('配置导出成功，按任意键继续...')
